
-- Membuat Database
CREATE DATABASE "INVENTORY_APP";

CREATE TABLE "R_STATE" (
    "SYS_ID_R_STATE" varchar (40) PRIMARY KEY,
    "NAME_R_STATE" varchar (40)
);

CREATE TABLE "TR_CATEGORY" (
    "SYS_ID_TR_CATEGORY" varchar (40) PRIMARY KEY,
    "NAME_TR_CATEGORY" varchar (40)
);

CREATE TABLE "TR_BARANG" (
    "SYS_ID_TR_BARANG" varchar (40) PRIMARY KEY,
    "NAME_TR_BARANG" varchar (40),
    "CATEGORY" varchar (40),
    "MERK" varchar (40),
    "TIPE" varchar (40),
    "SERIAL_NUMBER" varchar (40),
    "TANGGAL_PEMBELIAN" timestamp without time zone,
    "HARGA" NUMERIC(20,2),
    "KETERANGAN" text,
    "STATE" varchar (40)
);

ALTER TABLE "TR_BARANG" ADD CONSTRAINT "CATEGORY_fk" FOREIGN KEY ("CATEGORY") REFERENCES "TR_CATEGORY" ("SYS_ID_TR_CATEGORY");
ALTER TABLE "TR_BARANG" ADD CONSTRAINT "STATE_fk" FOREIGN KEY ("STATE") REFERENCES "R_STATE" ("SYS_ID_R_STATE");




INSERT INTO "TR_CATEGORY" ("SYS_ID_TR_CATEGORY", "NAME_TR_CATEGORY") VALUES (?, ?)
INSERT INTO "R_STATE" ("SYS_ID_R_STATE", "NAME_R_STATE") VALUES (?, ?)

INSERT INTO "TR_BARANG" (
    "SYS_ID_TR_BARANG", "NAME_TR_BARANG", "NUMBER", "CATEGORY", "MERK", "TIPE", "SERIAL_NUMBER", "TANGGAL_PEMBELIAN", "HARGA", "KETERANGAN", "STATE"
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)


SET NUMBERS DYNAMIC
ALTER TABLE "TR_BARANG"
ADD COLUMN "NUMBER" varchar(40)


CREATE SEQUENCE TR_BARANG_NUMBER_SEQUENCE
START 1
INCREMENT 1;

DROP SEQUENCE "TR_BARANG_NUMBER_SEQUENCE"

ALTER TABLE "TR_BARANG"
ALTER COLUMN "NUMBER"
SET DEFAULT (
    'INV-' || LPAD(nextval('TR_BARANG_NUMBER_SEQUENCE')::TEXT, 6, '0')
);




SELECT 
"SYS_ID_TR_BARANG", "NAME_TR_BARANG", "NUMBER", "CATEGORY", "MERK", "TIPE", "SERIAL_NUMBER", "TANGGAL_PEMBELIAN", "HARGA", "KETERANGAN", "STATE"
FROM "TR_BARANG"



SELECT 
    SUM(1) AS "TOTAL BARANG",

    SUM(CASE WHEN "STATE" = (
        SELECT "SYS_ID_R_STATE" FROM "R_STATE" WHERE "NAME_R_STATE" = 'Tersedia'
    ) THEN 1 ELSE 0 END) AS "BARANG_TERSEDIA",

    SUM(CASE WHEN "STATE" = (
        SELECT "SYS_ID_R_STATE" FROM "R_STATE" WHERE "NAME_R_STATE" = 'Dipinjam'
    ) THEN 1 ELSE 0 END) AS "BARANG_DIPINJAM",

    SUM(CASE WHEN "STATE" = (
        SELECT "SYS_ID_R_STATE" FROM "R_STATE" WHERE "NAME_R_STATE" = 'Rusak'
    ) THEN 1 ELSE 0 END) AS "BARANG_RUSAK"

FROM "TR_BARANG"



SELECT 
    g."NAME_TR_CATEGORY",
    (SELECT COUNT(*) FROM "TR_BARANG" b WHERE b."CATEGORY" = g."SYS_ID_TR_CATEGORY" ) AS "TOTAL_BARANG"
FROM "TR_CATEGORY" g;






SELECT 
b."SYS_ID_TR_BARANG", b."NAME_TR_BARANG", b."NUMBER", b."CATEGORY" AS "CATEGORY_ID", tc."NAME_TR_CATEGORY" AS "CATEGORY_NAME", b."MERK", b."TIPE", b."SERIAL_NUMBER", b."TANGGAL_PEMBELIAN", b."HARGA", b."KETERANGAN", b."STATE" AS "STATE_ID", s."NAME_R_STATE" AS "STATE_NAME"
FROM "TR_BARANG" b
LEFT JOIN "R_STATE" s ON s."SYS_ID_R_STATE" = b."STATE"
LEFT JOIN "TR_CATEGORY" tc ON tc."SYS_ID_TR_CATEGORY" = b."CATEGORY";

